export const IDENTITY_PATTERNS = {
  AUTH_LOGIN: 'identity.auth.login',
  AUTH_REGISTER: 'identity.auth.register',
  AUTH_FORGOT_PASSWORD: 'identity.auth.forgot_password',
  AUTH_RESET_PASSWORD: 'identity.auth.reset_password',
  USER_FIND_ALL: 'identity.user.find_all',
  USER_FIND_BY_ID: 'identity.user.find_by_id',
  USER_CREATE: 'identity.user.create',
  USER_UPDATE: 'identity.user.update',
  USER_COUNT_ACTIVE: 'identity.user.count_active',
  USER_UPDATE_AVATAR: 'identity.user.update_avatar',
  RBAC_PROFILE: 'identity.rbac.profile',
  RBAC_CATALOGS: 'identity.rbac.catalogs',
  PUSH_TOKEN_REGISTER: 'identity.push_token.register',
  PUSH_NOTIFY_USERS: 'identity.push.notify_users',
  PUSH_NOTIFY_EMAIL: 'identity.push.notify_email',
  PUSH_NOTIFY_ROLE: 'identity.push.notify_role',
  NOTIFICATION_FIND_ALL: 'identity.notification.find_all',
  NOTIFICATION_UNREAD_COUNT: 'identity.notification.unread_count',
  NOTIFICATION_MARK_READ: 'identity.notification.mark_read',
  NOTIFICATION_MARK_ALL_READ: 'identity.notification.mark_all_read',
} as const;
