export const IDENTITY_CLIENT = 'IDENTITY_CLIENT';
export const LEARNING_CLIENT = 'LEARNING_CLIENT';
export const CERTIFICATION_CLIENT = 'CERTIFICATION_CLIENT';
export const PAYMENT_CLIENT = 'PAYMENT_CLIENT';
