FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json* tsconfig.json nest-cli.json ./
COPY apps/certification-service ./apps/certification-service
COPY libs ./libs
RUN npm ci --no-audit --no-fund
RUN npx prisma generate --schema=apps/certification-service/prisma/schema.prisma
RUN npx nest build certification-service

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist/apps/certification-service ./dist/apps/certification-service
COPY --from=builder /app/apps/certification-service/prisma ./apps/certification-service/prisma
COPY --from=builder /app/apps/certification-service/src/prisma/generated ./apps/certification-service/src/prisma/generated
ENV NODE_ENV=production
CMD ["sh", "-c", "npx prisma migrate deploy --schema=apps/certification-service/prisma/schema.prisma && node dist/apps/certification-service/main"]
