export const LEARNING_PATTERNS = {
  COURSE_CREATE: 'learning.course.create',
  COURSE_FIND_ALL: 'learning.course.find_all',
  COURSE_FIND_PUBLISHED: 'learning.course.find_published',
  COURSE_FIND_PUBLISHED_ONE: 'learning.course.find_published_one',
  COURSE_COUNT_PUBLISHED: 'learning.course.count_published',
  COURSE_FIND_ONE: 'learning.course.find_one',
  COURSE_UPDATE: 'learning.course.update',
  COURSE_DELETE: 'learning.course.delete',
  COURSE_PUBLISH: 'learning.course.publish',
  COURSE_REVIEW_FIND_BY_COURSE: 'learning.course.review.find_by_course',
  COURSE_REVIEW_UPSERT: 'learning.course.review.upsert',
  COURSE_CERTIFICATE_ELIGIBILITY: 'learning.course.certificate_eligibility',
  COURSE_FAVORITE_TOGGLE: 'learning.course.favorite.toggle',
  COURSE_FAVORITE_FIND_MINE: 'learning.course.favorite.find_mine',

  PHASE_CREATE: 'learning.phase.create',
  PHASE_FIND_BY_COURSE: 'learning.phase.find_by_course',
  PHASE_DELETE: 'learning.phase.delete',

  LESSON_CREATE: 'learning.lesson.create',
  LESSON_FIND_ALL: 'learning.lesson.find_all',
  LESSON_FIND_ONE: 'learning.lesson.find_one',
  LESSON_UPDATE: 'learning.lesson.update',
  LESSON_DELETE: 'learning.lesson.delete',

  INSCRIPTION_CREATE: 'learning.inscription.create',
  INSCRIPTION_FIND_ALL: 'learning.inscription.find_all',
  INSCRIPTION_FIND_ONE: 'learning.inscription.find_one',
  INSCRIPTION_UPDATE: 'learning.inscription.update',
  INSCRIPTION_DELETE: 'learning.inscription.delete',
  INSCRIPTION_STATS_PUBLIC: 'learning.inscription.stats_public',
  INSCRIPTION_FIND_IDS_BY_SCOPE: 'learning.inscription.find_ids_by_scope',
  INSCRIPTION_CERTIFICATE_ELIGIBILITY: 'learning.inscription.certificate_eligibility',

  PROGRESS_FIND_BY_INSCRIPTION: 'learning.progress.find_by_inscription',
  PROGRESS_FIND_ALL: 'learning.progress.find_all',

  CALIFICATION_CREATE: 'learning.calification.create',
  CALIFICATION_FIND_ALL: 'learning.calification.find_all',
  CALIFICATION_FIND_ONE: 'learning.calification.find_one',
  CALIFICATION_UPDATE: 'learning.calification.update',
  CALIFICATION_DELETE: 'learning.calification.delete',

  NOTE_CREATE: 'learning.note.create',
  NOTE_FIND_BY_LESSON: 'learning.note.find_by_lesson',
  NOTE_UPDATE: 'learning.note.update',
  NOTE_DELETE: 'learning.note.delete',

  EVALUATION_CREATE: 'learning.evaluation.create',
  EVALUATION_FIND_ALL: 'learning.evaluation.find_all',
  EVALUATION_FIND_ONE: 'learning.evaluation.find_one',
  EVALUATION_SUBMIT_ATTEMPT: 'learning.evaluation.submit_attempt',
  EVALUATION_FIND_MY_ATTEMPT: 'learning.evaluation.find_my_attempt',

  COMMENT_FIND_BY_COURSE: 'learning.comment.find_by_course',
  COMMENT_CREATE: 'learning.comment.create',
  COMMENT_TOGGLE_LIKE: 'learning.comment.toggle_like',
  COMMENT_DELETE: 'learning.comment.delete',

  TASK_FIND_PENDING: 'learning.task.find_pending',
  LESSON_SET_COMPLETED: 'learning.lesson.set_completed',

  EVT_INSCRIPTION_COMPLETED: 'learning.inscription.completed',

  LIVE_SESSION_CREATE: 'learning.live_session.create',
  LIVE_SESSION_FIND_ALL: 'learning.live_session.find_all',
  LIVE_SESSION_FIND_ONE: 'learning.live_session.find_one',
  LIVE_SESSION_UPDATE: 'learning.live_session.update',
  LIVE_SESSION_DELETE: 'learning.live_session.delete',
  LIVE_SESSION_FIND_NEXT_PUBLIC: 'learning.live_session.find_next_public',
  LIVE_SESSION_START: 'learning.live_session.start',

  CHAT_SEND: 'learning.chat.send',
  CHAT_FIND_HISTORY: 'learning.chat.find_history',
  CHAT_CLEAR_HISTORY: 'learning.chat.clear_history',
  CHAT_LIST_CONVERSATIONS: 'learning.chat.list_conversations',
  CHAT_DELETE_FROM: 'learning.chat.delete_from',

  ALEXA_SCHEDULE_CLASS: 'learning.alexa.schedule_class',
  ALEXA_GENERATE_TRIVIA: 'learning.alexa.generate_trivia',
  ALEXA_SAVE_TRIVIA_RESULT: 'learning.alexa.save_trivia_result',
  ALEXA_GET_PROGRESS: 'learning.alexa.get_progress',
} as const;
