FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json tsconfig.json nest-cli.json ./
COPY apps/gateway ./apps/gateway
COPY libs ./libs
RUN npm install --no-audit --no-fund
RUN npx nest build gateway

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist/apps/gateway ./dist/apps/gateway
ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "dist/apps/gateway/main"]
